"""initial schema

Revision ID: 815042be5ea2
Revises:
Create Date: 2026-07-07 05:41:13.765831
"""

revision = "815042be5ea2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
